# Generated by Django 3.2.8 on 2021-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bet_comment_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
    ]
