# Generated by Django 3.2.8 on 2021-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_lot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.URLField(),
        ),
    ]
