# Generated by Django 3.2.8 on 2021-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_lot_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='photo',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
