# Generated by Django 3.2.8 on 2021-11-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211118_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='category',
        ),
    ]
