# Generated by Django 3.2.8 on 2021-11-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_lot_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
