# Generated by Django 3.2.8 on 2021-11-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211125_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_title',
        ),
    ]
