# Generated by Django 3.2.8 on 2021-11-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20211125_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='first_bet',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='first_bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.bet'),
        ),
    ]
