# Generated by Django 3.2.8 on 2021-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_lot_first_bet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='first_bet',
            new_name='bet',
        ),
        migrations.AlterField(
            model_name='lot',
            name='first_bet',
            field=models.FloatField(),
        ),
    ]
