# Generated by Django 3.2.8 on 2021-11-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20211126_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='first_bet',
            field=models.IntegerField(),
        ),
    ]
