# Generated by Django 3.2.8 on 2021-11-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_lot_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='category',
        ),
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='auctions.Category'),
        ),
    ]
