# Generated by Django 3.2.8 on 2021-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20211129_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_title']},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ManyToManyField(related_name='lots', to='auctions.Category'),
        ),
    ]
