# Generated by Django 3.2.8 on 2021-11-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20211129_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={},
        ),
    ]
