# Generated by Django 3.2.8 on 2021-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.IntegerField(null=True),
        ),
    ]
