# Generated by Django 3.2.8 on 2021-12-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20211202_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lot', to=settings.AUTH_USER_MODEL),
        ),
    ]
