# Generated by Django 3.2.8 on 2021-12-08 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_lot_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='client',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bet',
            name='lot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bet', to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet',
            field=models.IntegerField(blank=True),
        ),
    ]
