# Generated by Django 3.2.8 on 2021-12-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_lot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='status',
            new_name='is_open',
        ),
    ]
