# Generated by Django 3.2.8 on 2021-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_rename_status_lot_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='default_bet',
            field=models.IntegerField(default=1),
        ),
    ]
