# Generated by Django 3.2.8 on 2021-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_lot_default_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='default_bet',
            field=models.IntegerField(),
        ),
    ]
