# Generated by Django 3.2.8 on 2021-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_lot_default_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='default_bet',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
