# Generated by Django 3.2.8 on 2021-12-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20211216_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.lot'),
        ),
    ]
