# Generated by Django 3.2.8 on 2021-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_comment_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
