# Generated by Django 3.2.8 on 2021-12-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_alter_lot_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='lot',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auctions.lot'),
        ),
    ]
